

escreva = [{'nome':'KauÃª Araujo','idade':'23','estado':'SC'},
{'nome':'Giovanna Cunha','idade':'21','estado':'SC'},
{'nome':'Samuel Fernandes','idade':'19','estado':'SC'},
{'nome':'Kauan Ferreira','idade':'30','estado':'SC'},
{'nome':'Brenda Sousa','idade':'50','estado':'SC'},
{'nome':'Carolina Sousa','idade':'20','estado':'SC'},
{'nome':'Marcos Rodrigues','idade':'33','estado':'SC'},
{'nome':'Renan Goncalves' ,'idade': '21' ,'estado': 'SC'},
{'nome':'Estevan Rocha' ,'idade': '21' ,'estado': 'SC'},
{'nome':'Daniel Pinto' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Davi Barros' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Giovanna Costa' ,'idade': '22' ,'estado': 'SC'},
{'nome':'KauÃ£ Ferreira' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Maria Ferreira' ,'idade': '26' ,'estado': 'SC'},
{'nome':'Isabelle Cardoso' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Gabrielly Cunha' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Ãgatha Almeida' ,'idade': '26' ,'estado': 'SC'},
{'nome':'Luis Dias' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Arthur Oliveira' ,'idade': '41' ,'estado': 'SC'},
{'nome':'Isabelle Ribeiro' ,'idade': '38' ,'estado': 'SC'},
{'nome':'Miguel Rodrigues' ,'idade': '39' ,'estado': 'SC'},
{'nome':'Leonardo Silva' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Julia Castro' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Breno Pereira' ,'idade': '19' ,'estado': 'SC'},
{'nome':'JoÃ£o Gomes' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Leila Costa' ,'idade': '21' ,'estado': 'SC'},
{'nome':'Anna Costa' ,'idade': '30' ,'estado': 'GO'},
{'nome':'Eduardo Souza' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Davi Ferreira' ,'idade': '33' ,'estado': 'SC'},
{'nome':'Matheus Barbosa' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Aline Martins' ,'idade': '33' ,'estado': 'SC'},
{'nome':'Nicole Sousa' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Carlos Martins' ,'idade': '28' ,'estado':'SC' },
{'nome':'VinÃ­cius Azevedo' ,'idade': '34' ,'estado': 'SC'},
{'nome':'Ana Castro' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Amanda Pinto' ,'idade': '29' ,'estado': 'SC'},
{'nome':'Guilherme Oliveira' ,'idade': '30' ,'estado': 'SP'},
{'nome':'Rafael Castro' ,'idade': '36' ,'estado': 'SC'},
{'nome':'Douglas Barros' ,'idade': '30' ,'estado': 'SC'},
{'nome':'Paulo Cunha' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Sophia Correia' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Lucas Araujo' ,'idade': '54' ,'estado': 'SC'},
{'nome':'Emily Ferreira' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Isabelle Dias' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Camila Lima' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Isabela Araujo' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Emilly Sousa' ,'idade': '19' ,'estado': 'SP'},
{'nome':'Kaua Ferreira' ,'idade': '26' ,'estado': 'SP'},
{'nome':'Alex Sousa' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Danilo Conrado' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Miguel Fernandes' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Nicolas Araujo' ,'idade': '28' ,'estado': 'SP'},
{'nome':'Gabrielly Cardoso' ,'idade': '40' ,'estado': 'SC'},
{'nome':'JosÃ© Silva' ,'idade': '48' ,'estado': 'SC'},
{'nome':'Yasmin Dias' ,'idade': '21' ,'estado': 'SC'},
{'nome':'Nicolash Almeida' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Fernanda Santos' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Beatrice Araujo' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Thiago Carvalho' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Isabella Ribeiro' ,'idade': '25' ,'estado': 'SC'},
{'nome':'Enzo Barros' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Manuela Dias' ,'idade': '35' ,'estado': 'SC'},
{'nome':'Nicolash Cunha' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Paulo Gomes' ,'idade': '19' ,'estado': 'SC'},
{'nome':'VitÃ³ria Fernandes' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Bianca Castro' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Amanda Cardoso' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Felipe Fernandes' ,'idade': '22' ,'estado': 'SP'},
{'nome':'Livia Rodrigues' ,'idade': '18' ,'estado': 'SC'},
{'nome':'KauÃ£ Cardoso' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Marisa Cardoso' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Anna Carvalho' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Rafael Araujo' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Matilde Barros' ,'idade': '25' ,'estado': 'SC'},
{'nome':'Evelyn Rodrigues' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Kauan Dias' ,'idade': '29' ,'estado': 'SC' },
{'nome':'Camila Barros' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Diego Pereira' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Julian Cardoso' ,'idade': '40' ,'estado': 'SC'},
{'nome':'Anna Costa' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Anna Almeida' ,'idade': '26' ,'estado': 'SC'},
{'nome':'Lara Fernandes' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Mateus Silva' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Raissa Ribeiro' ,'idade': '30' ,'estado': 'SC'},
{'nome':'Eduarda Barros' ,'idade': '21' ,'estado': 'SC'},
{'nome':'Enzo Barros' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Kai Dias' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Carolina Goncalves' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Vitor Gomes' ,'idade': '42' ,'estado': 'SC'},
{'nome':'Sofia Alves' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Evelyn Carvalho' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Julian Cardoso' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Rafaela Cunha' ,'idade': '18' ,'estado': 'SC'},
{'nome':'VitÃ³ria Dias' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Anna Santos' ,'idade': '32' ,'estado': 'SC'},
{'nome':'Miguel Correia' ,'idade': '29' ,'estado':'SC'},
{'nome':'Manuela Gomes' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Fernanda Almeida' ,'idade': '26' ,'estado': 'SC'},
{'nome':'Paulo Rocha' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Danilo Correia' ,'idade': '47' ,'estado': 'SC'},
{'nome':'Maria Oliveira' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Bruna Martins' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Gabrielle Rodrigues' ,'idade': '18' ,'estado':'SC'},
{'nome':'Emilly Barros' ,'idade': '37' ,'estado': 'SC'},
{'nome':'Ãgatha Sousa' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Fernanda Barbosa' ,'idade': '31' ,'estado': 'SC'},
{'nome':'Eduardo Oliveira' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Diego Castro' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Igor Martins' ,'idade': '21' ,'estado': 'SC'},
{'nome':'ThaÃ­s Barbosa' ,'idade': '31' ,'estado': 'SC'},
{'nome':'Guilherme Ribeiro' ,'idade': '29' ,'estado': 'SC'},
{'nome':'Mariana Rodrigues' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Estevan Cavalcanti' ,'idade': '26' ,'estado': 'SP'},
{'nome':'AndrÃ© Souza' ,'idade': '26' ,'estado': 'SC'},
{'nome':'AndrÃ© Melo' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Isabella Carvalho' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Ryan Barbosa' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Isabelle Rocha' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Sarah Rodrigues' ,'idade': '49' ,'estado': 'SC'},
{'nome':'Gabrielle Costa' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Ryan Souza' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Diego Barbosa' ,'idade': '25' ,'estado': 'RJ'},
{'nome':'Beatriz Alves' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Luiza Cunha' ,'idade': '21' ,'estado': 'SP'},
{'nome':'Marina Pinto' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Eduarda Silva' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Tiago Oliveira' ,'idade': '30' ,'estado': 'SC'},
{'nome':'JÃºlio Fernandes' ,'idade': '26' ,'estado': 'SC'},
{'nome':'LetÃ­cia Ribeiro' ,'idade': '34' ,'estado': 'SC'},
{'nome':'TÃ¢nia Rodrigues' ,'idade': '32' ,'estado': 'SC'},
{'nome':'JoÃ£o Cunha' ,'idade': '18' ,'estado': 'SC'},
{'nome':'LuÃ­s Lima' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Gabrielly Cunha' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Murilo Gomes' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Nicolas Almeida' ,'idade': '33' ,'estado': 'SC'},
{'nome':'Camila Cardoso' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Larissa Ribeiro' ,'idade': '25' ,'estado': 'SP'},
{'nome':'AntÃ´nio Cavalcanti' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Bianca Azevedo' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Carla Barros' ,'idade': '28' ,'estado': 'SC' },
{'nome':'Arthur Barbosa' ,'idade': '28' ,'estado': 'SC'},
{'nome':'Tiago Barros' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Marcos Souza' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Emily Cunha' ,'idade': '35' ,'estado': 'SC'},
{'nome':'Maria Alves' ,'idade': '19' ,'estado': 'SP'},
{'nome':'Renan Ferreira' ,'idade': '38' ,'estado':'SC'},
{'nome':'Mariana Oliveira' ,'idade': '17' ,'estado':'SC'},
{'nome':'Rafael Costa' ,'idade': '18' ,'estado':'SC'},
{'nome':'JosÃ© Santos' ,'idade': '27' ,'estado':'RJ'},
{'nome':'Livia Araujo' ,'idade': '39' ,'estado':'SC'},
{'nome':'Bianca Cunha' ,'idade': '35' ,'estado':'SC'},
{'nome':'Alice Lima' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Leila Silva' ,'idade': '22' ,'estado': 'SC'},
{'nome':'Ãgatha Santos' ,'idade': '26' ,'estado': 'SC'},
{'nome':'Melissa Cunha' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Gustavo Costa' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Beatrice Pereira' ,'idade': '21' ,'estado': 'SC'},
{'nome':'OtÃ¡vio Fernandes' ,'idade': '30' ,'estado': 'SC'},
{'nome':'Daniel Melo' ,'idade': '55' ,'estado':'SC'},
{'nome':'Matheus Alves' ,'idade': '50' ,'estado':'SC'},
{'nome':'Paulo Goncalves' ,'idade': '24' ,'estado':'SC'},
{'nome':'ThaÃ­s Cavalcanti' ,'idade': '20' ,'estado':'AL' },
{'nome':'Renan Cunha' ,'idade': '22' ,'estado': 'SC'},
{'nome':'AntÃ´nio Ribeiro' ,'idade': '24' ,'estado':'SC'},
{'nome':'Sofia Rodrigues' ,'idade': '20' ,'estado':'SC'},
{'nome':'Vitor Costa' ,'idade': '23' ,'estado':'SC'},
{'nome':'Rafael Pinto' ,'idade': '28' ,'estado':'SC'},
{'nome':'Nicole Carvalho' ,'idade': '33' ,'estado':'SC'},
{'nome':'Nicole Ferreira' ,'idade': '22' ,'estado':'SC'},
{'nome':'KauÃª Souza' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Fernanda Ribeiro' ,'idade': '46' ,'estado':'SC'},
{'nome':'Rafael Martins' ,'idade': '32' ,'estado':'SC'},
{'nome':'Emilly Pereira' ,'idade': '21' ,'estado':'SC'},
{'nome':'Rebeca Araujo' ,'idade': '20' ,'estado':'SC'},
{'nome':'Aline Cunha' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Julieta Pinto' ,'idade': '33' ,'estado': 'SC'},
{'nome':'Luiz Gomes' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Giovanna Silva' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Gabriela Correia' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Alice Gomes' ,'idade': '27' ,'estado': 'SC'},
{'nome':'Brenda Gomes' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Arthur Goncalves' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Leonor Oliveira' ,'idade': '32' ,'estado': 'SC'},
{'nome':'Pedro Barros' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Gabrielle Rocha' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Heitor Goncalves' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Aline Fernandes' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Estevan Rodrigues' ,'idade': '19' ,'estado':'SC'},
{'nome':'Livia Cunha' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Matheus Carvalho' ,'idade': '18' ,'estado':'SC'},
{'nome':'Erick Santos' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Marina Costa' ,'idade': '34' ,'estado': 'SC'},
{'nome':'JosÃ© Goncalves' ,'idade': '30' ,'estado':'SC'},
{'nome':'Ana Correia' ,'idade': '24' ,'estado':'SC'},
{'nome':'Kauan Martins' ,'idade': '23' ,'estado':'SC'},
{'nome':'Caio Melo' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Marina Goncalves' ,'idade': '17' ,'estado': 'SC'},
{'nome':'Leonor Gomes' ,'idade': '17' ,'estado': 'SC'},
{'nome':'OtÃ¡vio Ferreira' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Kai Carvalho' ,'idade': '25' ,'estado': 'SC'},
{'nome':'Arthur Fernandes' ,'idade': '26' ,'estado':'SC'},
{'nome':'Rafael Cavalcanti' ,'idade': '19' ,'estado':'SC'},
{'nome':'Matilde Rodrigues' ,'idade': '18' ,'estado':'SC'},
{'nome':'Ãgatha Souza' ,'idade': '23' ,'estado':'SC'},
{'nome':'TomÃ¡s Cunha' ,'idade': '19' ,'estado':'SC'},
{'nome':'Luana Rodrigues' ,'idade': '29' ,'estado':'SC'},
{'nome':'Gabrielly Azevedo' ,'idade': '25' ,'estado':'SC'},
{'nome':'Clara Lima' ,'idade': '23' ,'estado':'SC'},
{'nome':'Emilly Fernandes' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Fernandu Vieira' ,'idade': '29' ,'estado': 'SC'},
{'nome':'Victor Cardoso' ,'idade': '18' ,'estado': 'SC'},
{'nome':'Leonardo Alves' ,'idade': '20' ,'estado': 'SC'},
{'nome':'Carlos Martins' ,'idade': '24' ,'estado': 'SC'},
{'nome':'Rodrigo Carvalho' ,'idade': '24' ,'estado':'SC'},
{'nome':'Estevan Castro' ,'idade': '23' ,'estado':'SC'},
{'nome':'Giovanna Castro' ,'idade': '32' ,'estado':'SC'},
{'nome':'Matilde Carvalho' ,'idade': '33' ,'estado':'SC'},
{'nome':'Martim Almeida' ,'idade': '24' ,'estado':'SC'},
{'nome':'Gabriel Costa' ,'idade': '20' ,'estado':'SC'},
{'nome':'Fernanda Goncalves' ,'idade': '24' ,'estado':'SC'},
{'nome':'JÃºlia Azevedo' ,'idade': '35' ,'estado':'AM'},
{'nome':'Alex Santos' ,'idade': '21' ,'estado':'SC'},
{'nome':'VinÃ­cius Fernandes' ,'idade': '28' ,'estado':'SC'},
{'nome':'Estevan Alves' ,'idade': '30' ,'estado': 'PR'},
{'nome':'Luana Santos' ,'idade': '23' ,'estado': 'SC'},
{'nome':'Beatriz Rodrigues' ,'idade': '18' ,'estado':'SC'},
{'nome':'LuÃ­s Almeida' ,'idade': '19' ,'estado': 'SC'},
{'nome':'Arthur Cardoso' ,'idade': '29' ,'estado': 'SP'},
{'nome':'Samuel Ribeiro' ,'idade': '25' ,'estado': 'SC'},
{'nome':'Martim Azevedo' ,'idade': '19' ,'estado': 'SC'}]



print(len(escreva))